// _____________________________________________________________________________
//
//  Autogenerated Game Database Source
//  Title: A Mansao Misteriosa
//  Author: Clean-Room Engineer
// _____________________________________________________________________________

#include "game_data.h"

// --- Mensagens ---
static const Game_Message s_msg_0 = { 11, "A Mansao Misteriosa - Uma aventura em texto para MSX." };
static const Game_Message s_msg_1 = { 30, "Voce riscou um fosforo e acendeu a vela. Uma luz suave ilumina o ambiente." };
static const Game_Message s_msg_2 = { 31, "Voce assoprou e apagou a vela." };
static const Game_Message s_msg_3 = { 32, "Pegou." };
static const Game_Message s_msg_4 = { 33, "Soltou no chao." };
static const Game_Message s_msg_5 = { 34, "Guardou dentro da mala." };
static const Game_Message s_msg_6 = { 35, "Voce usou a chave e destrancou o portao sul\133 Parabens, voce venceu\133" };
static const Game_Message* const s_messages[] = {
    &s_msg_0,
    &s_msg_1,
    &s_msg_2,
    &s_msg_3,
    &s_msg_4,
    &s_msg_5,
    &s_msg_6,
};

// --- Objetos ---
static const Game_Object s_obj_0 = { 1, 0, 0x00, "LOCAL", "O local onde voce se encontra." };
static const Game_Object s_obj_1 = { 2, 1, 0x03, "VELA/VELAS", "Uma vela de cera amarelada." };
static const Game_Object s_obj_2 = { 3, 2, 0x01, "MALA/BOLSA", "Uma mala de couro aberta para guardar objetos." };
static const Game_Object s_obj_3 = { 4, 3, 0x03, "CHAVE/CHAVES", "Uma chave de bronze pesada." };
static const Game_Object s_obj_4 = { 5, 1, 0x03, "FOSFORO/FOSFOROS", "Uma caixinha com fosforos." };
static const Game_Object* const s_objects[] = {
    &s_obj_0,
    &s_obj_1,
    &s_obj_2,
    &s_obj_3,
    &s_obj_4,
};

// --- Posições ---
static const Game_Position s_pos_0 = { 1, { 2, 0, 0, 0, 0, 0, 0, 0 }, "Voce esta no grande hall de entrada de uma antiga mansao. Ao norte ha uma sala de estar. A saida ao sul esta trancada." };
static const Game_Position s_pos_1 = { 2, { 0, 1, 3, 4, 0, 0, 0, 0 }, "Voce esta em uma confortavel sala de estar com lareira apagada. Ha passagens para o sul, leste e oeste." };
static const Game_Position s_pos_2 = { 3, { 0, 0, 0, 2, 0, 0, 0, 0 }, "Uma biblioteca silenciosa com estantes repletas de livros empoeirados. A saida fica a oeste." };
static const Game_Position s_pos_3 = { 4, { 0, 0, 2, 0, 0, 0, 0, 0 }, "Um porao escuro e gelado sob a mansao. A escada para a sala de estar sobe a leste." };
static const Game_Position* const s_positions[] = {
    &s_pos_0,
    &s_pos_1,
    &s_pos_2,
    &s_pos_3,
};

// --- Funções ---
static const Game_Instruction s_func_inst_0[] = {
    { 9, 1, 1, 0 },
    { 9, 10, 0, 0 },
    { 34, 0, 0, 0 },
};
static const Game_Function s_func_0 = { 1, s_func_inst_0, 3 };

static const Game_Instruction s_func_inst_1[] = {
    { 15, 0, 3, 0 },
    { 1, 19, 0, 0 },
    { 2, 0, 0, 0 },
    { 13, 8, 4, 7 },
    { 19, 0, 0, 0 },
    { 1, 32, 0, 0 },
    { 2, 0, 0, 0 },
    { 1, 21, 0, 0 },
    { 2, 0, 0, 0 },
};
static const Game_Function s_func_1 = { 6, s_func_inst_1, 9 };

static const Game_Instruction s_func_inst_2[] = {
    { 17, 0, 3, 0 },
    { 1, 17, 0, 0 },
    { 2, 0, 0, 0 },
    { 25, 0, 0, 0 },
    { 1, 34, 0, 0 },
    { 2, 0, 0, 0 },
};
static const Game_Function s_func_2 = { 7, s_func_inst_2, 6 };

static const Game_Instruction s_func_inst_3[] = {
    { 17, 0, 3, 0 },
    { 1, 17, 0, 0 },
    { 2, 0, 0, 0 },
    { 18, 0, 0, 0 },
    { 1, 33, 0, 0 },
    { 2, 0, 0, 0 },
};
static const Game_Function s_func_3 = { 13, s_func_inst_3, 6 };

static const Game_Instruction s_func_inst_4[] = {
    { 15, 0, 4, 0 },
    { 17, 0, 4, 0 },
    { 1, 19, 0, 0 },
    { 2, 0, 0, 0 },
    { 1, 20, 0, 0 },
    { 6, 0, 0, 0 },
    { 41, 46, 0, 0 },
    { 2, 0, 0, 0 },
};
static const Game_Function s_func_4 = { 14, s_func_inst_4, 8 };

static const Game_Function* const s_functions[] = {
    &s_func_0,
    &s_func_1,
    &s_func_2,
    &s_func_3,
    &s_func_4,
};

// --- Comandos ---
static const Game_Instruction s_cmd_inst_0[] = {
    { 17, 2, 3, 0 },
    { 1, 17, 0, 0 },
    { 2, 0, 0, 0 },
    { 9, 10, 1, 0 },
    { 1, 30, 0, 0 },
    { 2, 0, 0, 0 },
};
static const Game_Command s_cmd_0 = { 31, 2, 0, s_cmd_inst_0, 6 };

static const Game_Instruction s_cmd_inst_1[] = {
    { 16, 1, 3, 0 },
    { 1, 16, 0, 0 },
    { 2, 0, 0, 0 },
    { 17, 4, 6, 0 },
    { 1, 15, 0, 0 },
    { 2, 0, 0, 0 },
    { 1, 35, 0, 0 },
    { 31, 0, 0, 0 },
};
static const Game_Command s_cmd_1 = { 7, 0, 0, s_cmd_inst_1, 8 };

static const Game_Command* const s_commands[] = {
    &s_cmd_0,
    &s_cmd_1,
};

// --- Verbos Customizados ---
// --- Atalhos de Acentos (Top 10 mais frequentes) ---
static const u8 s_shortcuts[10] = {
    0x80, // Shift+0
    0x84, // Shift+1
    0x90, // Shift+2
    0x89, // Shift+3
    0x8A, // Shift+4
    0x8B, // Shift+5
    0xB0, // Shift+6
    0xB4, // Shift+7
    0x8D, // Shift+8
    0x8E, // Shift+9
};

// --- Base de Dados do Jogo ---
const Game_Database g_GameDatabase = {
    "A Mansao Misteriosa",
    1, // posicao_inicial
    5, // max_carregados
    3, // max_no_obj3
    s_positions,
    4,
    s_objects,
    5,
    s_commands,
    2,
    s_functions,
    5,
    s_messages,
    7,
    NULL,
    0,
    s_shortcuts
};
