// _____________________________________________________________________________
//
//  Autogenerated Game Database Header
//  Title: A Mansao Misteriosa (v1.0)
// _____________________________________________________________________________

#ifndef GAME_DATA_H
#define GAME_DATA_H

#include "game_types.h"

extern const Game_Database g_GameDatabase;

#endif // GAME_DATA_H
